### ISSUE TITLE
Usage of non-exposed pcap function

### ISSUE THREAD

**Issue by rnbwdsh** [aol/moloch#1303]
**Elasticsearch version**: irrelevant

**Moloch version**: 2.1

**OS name and version**: 5.3.8-1-MANJARO

**How was Moloch built/installed:** (rpm, deb, easybutton, ...): modified install for arch based systems: `./configure --with-libpcap=no --with-yara=no --with-glib2=no --with-pfring=no --with-curl=no --with-lua=no LIBS="-lpcap -lyara -llua -lcurl" GLIB2_CFLAGS="-I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include" GLIB2_LIBS="-lglib-2.0 -lgmodule-2.0 -lgobject-2.0 -lgio-2.0`

**Provide logs, stack traces and steps to reproduce**: (inside easybutton --install, while building capture)
``` 
gcc -rdynamic -ggdb -pthread main.o db.o yara.o http.o config.o parsers.o plugins.o field.o trie.o writers.o writer-inplace.o writer-disk.o writer-null.o writer-simple.o readers.o reader-libpcap-file.o reader-libpcap.o reader-tpacketv3.o reader-null.o packet.o session.o rules.o drophash.o pq.o -o moloch-capture \
            -u g_checksum_update -u g_hmac_update -u g_uri_unescape_segment \
    -lnl-genl-3 -lnl-3 \
    -lglib-2.0 -lgmodule-2.0 -lgobject-2.0 -lgio-2.0 -lmaxminddb -lnet -lrt -luuid -lpcre -lpcap -lyara -llua -lcurl thirdparty/http_parser.o thirdparty/js0n.o thirdparty/patricia.o -ldl -lssl -lcrypto -lyaml \
    -lm -lresolv -lmagic -lffi -lz
/usr/bin/ld: reader-libpcap-file.o: in function `reader_libpcapfile_opened':
/home/m/IdeaProjects/moloch/capture/reader-libpcap-file.c:562: undefined reference to `dlt_to_linktype'
/usr/bin/ld: reader-libpcap.o: in function `reader_libpcap_start':
/home/m/IdeaProjects/moloch/capture/reader-libpcap.c:97: undefined reference to `dlt_to_linktype'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:41: all] Error 1
make[1]: Leaving directory '/home/m/IdeaProjects/moloch/capture'
make: *** [Makefile:329: all-recursive] Error 1
MOLOCH: make failed
```

**Problem:** The used function is only exposed in the (statically linked) .a version of the pcap lib, but not in the .so, as it's not (yet) exposed in the pcap lib, or in any pcap.h. You can test this with `objdump -t libpcap.a | grep dlt` vs `objdump -T libpcap.so | grep dlt`

This PR over there fixes it: https://github.com/the-tcpdump-group/libpcap/pull/882, in the meantime a copy of the fixed libpcap.so is hosted at https://öä.eu/libpcap.so

This issue is a pre-requisite for my efforts to make it arch-linux installable / non-statically-linked installable on systems whose package managers support the according dependencies.

**Comment by guyharris** [comment]
> **Problem:** The used function is only exposed in the (statically linked) .a version of the pcap lib,

The only reason that it's "exposed" is that there is no mechanism to specify internal symbols that can be used from multiple object files within a library but that are not exported by the library for a static library, as can be done for dynamically-linked libraries.  If such a mechanism were available for static libraries, believe me, I would have used it.

If we don't declare a routine in `pcap/pcap.h`, we do not guarantee that it will continue to be available, or that it will have a stable ABI or API, so we do not guarantee that it will be usable even by people who link statically to get at the innards of libpcap.

In this *particular* case, especially given that future APIs to fully support pcapng files and capturing in a form that supplies pcapng-style information will use LINKTYPE_ values rather than DLT_ values (which are only exported because libpcap was BPF-oriented and dealt with DLT_ values; unfortunately, those values can't be used in capture files because the numerical values for some link-layer types differ between OSes), providing APIs to map between them might be useful.

In general, however, people should *not* depend on anything that they discover in the libpcap source but that's not documented in a man page; we guarantee API (and ABI!) stability for routines documented in the man page, but *all* other routines are internal routines subject to API/ABI change or removal.

**Comment by guyharris** [comment]
So is `pcapFileHeader.linktype` supposed to be a LINKTYPE_ value or a DLT_ value?

On [line 208 of capture-tpacketv3.c](https://github.com/aol/moloch/blob/master/capture/reader-tpacketv3.c#L208), it's passed to `pcap_open_dead()`, which takes a DLT_ value, not a LINKTYPE_ value, as an argument, so in that case it's presumably a DLT_ value.

However:

On [line 97 of reader-libpcap.c](https://github.com/aol/moloch/blob/master/capture/reader-libpcap.c#L97), `moloch_packet_set_linksnap()` is passed the result of `dlt_to_linktype(pcap_datalink(pcaps[0])) | pcap_datalink_ext(pcaps[0])`, which 1) maps a DLT_ value to a LINKTYPE_ value and 2) ORs in the "extension" bits, so it's neither a valid DLT_ value nor a valid LINKTYPE_ value, and `moloch_packet_set_linksnap()` sets pcapFileHeader.linktype` to that value.

On [line 562 of reader-libpcap-file.c](https://github.com/aol/moloch/blob/master/capture/reader-libpcap-file.c#L562), the same thing is done.

On [line 128 of reader-snf.c](https://github.com/aol/moloch/blob/master/capture/plugins/snf/reader-snf.c#L124), `DLT_EN10MB` is passed to `moloch_packet_set_linksnap()`, again indicating that it's a DLT_ value.

On [line 94 of reader-daq.c](https://github.com/aol/moloch/blob/master/capture/plugins/daq/reader-daq.c#L94), the result of `daq_get_datalink_type()` is passed to `moloch_packet_set_linksnap()`.  `daq_get_datalink_type()` returns a DLT_ value.

I would recommend that line 97 of reader-libpcap.c be changed to

        moloch_packet_set_linksnap(pcap_datalink(pcaps[0]), pcap_snapshot(pcaps[0]));

and that line 562 of reader-libpcap-file.c be changed to

    moloch_packet_set_linksnap(pcap_datalink(pcap), pcap_snapshot(pcap));

That would eliminate the only calls to `dlt_to_linktype()`; there are no calls to `linktype_to_dlt()`, so neither of them would be necessary after that change.

**Comment by awick** [comment]
@guyharris thank you for spending so much time on this.  pcapFileHeader (and pcapFileHeader.linktype) are used both for input and output, which is probably why its confusing and mixing types.  I was trying to replace pcap_dump_open which does the magic equivalent of `dlt_to_linktype(pcap_datalink(pcaps[0])) | pcap_datalink_ext(pcaps[0])` and I couldn't figure out anyway to do it without calling that dlt routine.

**Comment by guyharris** [comment]
> @guyharris thank you for spending so much time on this. pcapFileHeader (and pcapFileHeader.linktype) are used both for input and output

That should be fixed.

The only code that should have a pcap file header is in the writers, and it should be private to the writers.

For *input* streams, you should keep track of the DLT_ value (not a synthesized pcap file network type value), the snapshot length, and the "extension" information.  That should be passed to the writers, which should, if writing a pcap file stream, synthesize the network type value to be written to the file themselves.

The mapping from a DLT_ value to the LINKTYPE_ value to be combined with the "extension" value should be done by your own code.  To quote the comment that was in `pcap/bpf.h` in older versions of libpcap and `pcap/dlt.h` in newer versions (included, in both cases, by `pcap/pcap.h`, so you don't need to worry about including either of those files):

    /*
     * Values starting with 104 are used for newly-assigned link-layer
     * header type values; for those link-layer header types, the DLT_
     * value returned by pcap_datalink() and passed to pcap_open_dead(),
     * and the LINKTYPE_ value that appears in capture files, are the
     * same.
     *
     * DLT_MATCHING_MIN is the lowest such value; DLT_MATCHING_MAX is
     * the highest such value.
     */

The rest of the header indicates which other values have to be mapped from the per-platform DLT_ values to the platform-independent LINKTYPE_ values; the LINKTYPE_ values are given on [the tcpdump.org link-layer header types page](https://www.tcpdump.org/linktypes.html).

Anybody reading or writing pcap files should do the mapping themselves, and not depend on libpcap's help (people who want to depend on libpcap should use the pcap_dump_ routines).

**Comment by rnbdsh** [comment]
I am pretty new to the project and pcap-internals like LINKTYPE_ vs DLT, so I don't fully understand the changes that would be required to fix this. But do I understand the situation correctly:
1. The current handling isn't fully correct anyways, and removing the (.so invalid) reference to dlt_to_linktype woudln't change the situation
2. The current handling is done like this because it's used in readers and writers, even though only writers should require it?
3. The correct solution would be to manually do the mapping with the help of pcap_dump_ routines?

I'd like to contribute to solve this issue, to get arch linux compatibility / a full .so-install working, but I don't fully grasp what would be the fix. Can you give more details on what would be required?

**Comment by guyharris** [comment]
In libpcap, there are two sets of values identifying link-layer header types.

DLT_ values are the values used in all current libpcap APIs; they were originally defined by the LBL group that created tcpdump and libpcap, but once various \*BSDs (and, later, Mac OS X/OS X/macOS) picked up the BPF driver code from that group, they started defining their own DLT_ value, resulting in some DLT_XXX `#define`s having different numerical values on different platforms.

That meant that using DLT_ values in pcap files would be a Bad Idea, as, for some "link-layer header type" values in the file header, the correct interpretation of the packet data would depend on which OS wrote the file, which is Not Good.

One change would have been to have libpcap define DLT_ values itself, but that would mean its definition of DLT_ values might differ, on some OSes, from the OS's own definition, which would also Not Be Good.

So we (tcpdump.org - me, in this case) went with another choice.

libpcap *does* define DLT_ values, *but* it uses `#ifdef`s to define them, on platforms that include the BPF driver, to the values used on that platform.

It *also* defines  a set of LINKTYPE_ values.  Those values are the values that are used in pcap and pcapng files; they are defined by tcpdump.org, and, for any given link-layer header type, there is a single numerical value, used on all platforms.  Those are not exported in a header file, but are listed on [the tcpdump.org link-layer header types page](https://www.tcpdump.org/linktypes.html).  For each type, it lists the name and numerical value for the LINKTYPE_, the name but *not* the numerical value for the corresponding DLT_ (as the numerical value may be platform-dependent), and a description of the header.

In most cases, for a given link-layer header type, the numerical LINKTYPE_ value and the numerical DLT_ value, on all platforms, are the same.  At this point, the \*BSDs and macOS pick up our DLT_ values for new link-layer types, but continue to provide their own DLT_ values in older link-layer types, including the ones for which different Ones provide different numerical values for the same DLT_.

The LINKTYPE_ values are not *currently* used by any libpcap APIs, and existing APIs will continue forever to use DLT_ values (tcpdump.org's goal is to preserve not only API compatibility, but *ABI* compatibility).

libpcap has internal routines that map between LINKTYPE_ and DLT_ values.

The Moloch code to capture packets using libpcap, and to read capture files using libpcap, uses libpcap APIs, and thus deals with DLT_s, not LINKTYPE_s.  See capture/reader-libpcap-file.c and capture/reader-libpcap.c.

The Moloch code to capture packets directly using Linux TPACKET_V3 (rather than using libpcap and having it use TPACKET_V3, which current versions of libpcap will do) sets the link-layer header type to 1, which happens to correspond both to LINKTYPE_ETHERNET and DLT_EN10MB (the "10MB" is historical, referring to standard Ethernet rather than the Xerox 3MB Ethernet with a different header; DLT_EN10MB is the right type for everything from StarLAN to 40GB and up).  You might want to change

    moloch_packet_set_linksnap(1, config.snapLen);

to

    moloch_packet_set_linksnap(DLT_EN10MB, config.snapLen);

in `reader_tpacketv3_init()`, to make it a little clearer.

The same applies to `reader_pfring_start()` in capture/plugins/pfring/reader-pfring.c.

`reader_snf_start()` in capture/plugins/snf/reader-snf.c already uses DLT_EN10MB.

`reader_daq_start()` in capture/plugins/daq/reader-daq.c passes the result of `daq_get_datalink_type()`; as per the above, `daq_get_datalink_type()` passes a DLT_ value.

So Moloch should have the first argument to `moloch_packet_set_linksnap()` be a DLT_ value, not a LINKTYPE_ value or a "what numerical value should be put into the network type of a pcap header" value.

This would mean that the reading/capturing code would not need to be aware of LINKTYPE_ values at all, and thus would neither need to use the *non*-API *internal* libpcap routines to map between DLT_ and LINKTYPE_ nor need to have its own code to do that mapping.

However, Moloch's code to *write* pcap files doesn't use libpcap.  The code in packet.c and writer-disk.c writes the file itself.

I'm guessing that, for the writer-disk.c code, this is because it doesn't just do simple sequential writing using the standard I/O library routines (as libpcap does), presumably for performance reasons.  Therefore, it should construct its own private pcap file header, and have its own code to map the DLT_ value use in the rest of Moloch to a network type value in that header.

The packet.c code could just use the libpcap routines for writing packets, but currently there's no way to preserve the additional metadata in the upper 16 bits of the network type value in the pcap header - some of which is also provided from options in pcapng blocks if a pcapng file is opened for reading.  So, for now, that could also use the same code to construct a private pcap file header.

As noted, in most cases a given LINKTYPE_'s corresponding DLT_ always has the same numerical value as the LINKTYPE_ does, so no mapping is needed for those.  The exceptions are:

- DLT_FR -> LINKTYPE_FRELAY;
- DLT_ATM_RFC1483 -> LINKTYPE_ATM_RFC1483;
- DLT_RAW -> LINKTYPE_RAW;
- DLT_SLIP_BSDOS -> LINKTYPE_SLIP_BSDOS;
- DLT_PPP_BSDOS -> LINKTYPE_PPP_BSDOS;
- DLT_C_HDLC -> LINKTYPE_C_HDLC;
- DLT_ATM_CLIP -> LINKTYPE_ATM_CLIP;
- DLT_PPP_SERIAL -> LINKTYPE_PPP_HDLC
- DLT_PPP_ETHER -> LINKTYPE_PPP_ETHER;
- DLT_PFSYNC -> LINKTYPE_PFSYNC;
- DLT_PKTAP -> LINKTYPE_PKTAP.

An optimization is to:

- check for DLT_PFSYNC and DLT_PKTAP, and map them;
- for values >= 104, do no mapping;
- for values <= 10 do no mapping;
- for other values, do the above mapping (yes, even for DLT_PFSYNC and DLT_PKTAP).

So, in answer to the questions:

- The current handling isn't fully correct anyways, and removing the (.so invalid) reference to dlt_to_linktype woudln't change the situation

Yes.

- The current handling is done like this because it's used in readers and writers, even though only writers should require it?

Yes.

- The correct solution would be to manually do the mapping with the help of pcap_dump_ routines?

The correct solution would be to do the mapping, when writing packets, with a routine written for Moloch, doing the above.  There's no pcap_dump_ routine to help you do the mapping, and those routines probably aren't usable for at least one code path doing the writing.

**Comment by rnbdsh** [comment]
Thanks @guyharris and @awick for the extensive explanation.

I had to learn a lot before being able to even start, but I think I implemented most of your changes...

Some things I'm still not sure about: 
1. Some of your mentioned dlt-to-linktype numbers are the same according to https://godoc.org/github.com/0intro/pcap , so I don't see the reason for a mapping. Also I don't fully get DLT_PFSYNC / DLT_PFSYNC1 / DLT_PFSYNC2, do they all map to LINKTYPE_PFSYNC (as well as the other 1/2 variants?)
2. Is it correct to copy these defines over from the PCAP project to this project? Seems odd to me. Also where do they go? packet.h?
3. Question about C, as I'm usually py/java: 
```
MolochPcapFileHdr_t cpy = pcapFileHeader; 
modify(cpy); 
memcpy(buf, &cpy, sizeof(MolochPcapFileHdr_t)); 
```
would be an acceptable, non-memory-leaking way of doing this, right? As the 24by copy-instance is only created on the stack?

**Comment by guyharris** [comment]
> Thanks @guyharris and @awick for the extensive explanation.
> 
> I had to learn a lot before being able to even start, but I think I implemented most of your changes...
> 
> Some things I'm still not sure about:
> 
> 1. Some of your mentioned dlt-to-linktype numbers are the same according to https://godoc.org/github.com/0intro/pcap , so I don't see the reason for a mapping.

Some of the DLT_ numbers in https://godoc.org/github.com/0intro/pcap don't match the values on some OSes.  As per the comment in libpcap's pcap/dlt.h:

    /*
     * Frame Relay; BSD/OS has a DLT_FR with a value of 11, but that collides
     * with other values.
     * DLT_FR and DLT_FRELAY packets start with the Q.922 Frame Relay header  
     * (DLCI, etc.).
     */
    #define DLT_FRELAY      107

if you're on an OS that defines DLT_FR, it's not necessarily defined as 107.  Your code is unlikely to be run on the now-defunct BSD/OS, so you may be able to avoid the DLT_FR -> LINKTYPE_FRELAY mapping.

DLT_ATM_RFC1483 is another "different in BSD/OS" value:

    /* 
     * These are types that are different on some platforms, and that
     * have been defined by <net/bpf.h> for ages.  We use #ifdefs to
     * detect the BSDs that define them differently from the traditional
     * libpcap <net/bpf.h>
     *    
     * XXX - DLT_ATM_RFC1483 is 13 in BSD/OS, and DLT_RAW is 14 in BSD/OS,   
     * but I don't know what the right #define is for BSD/OS.
     */
    #define DLT_ATM_RFC1483 11      /* LLC-encapsulated ATM */

So don't go by what https://godoc.org/github.com/0intro/pcap says; go by what libpcap's pcap/dlt.h says, as well as what various BSDs define.

> Also I don't fully get DLT_PFSYNC / DLT_PFSYNC1 / DLT_PFSYNC2, do they all map to LINKTYPE_PFSYNC (as well as the other 1/2 variants?)

More quotes from libpcap's pcap/dlt.h:

    /*
     * 18 is used for DLT_PFSYNC in OpenBSD, NetBSD, DragonFly BSD and
     * macOS; don't use it for anything else.  (FreeBSD uses 121, which
     * collides with DLT_HHDLC, even though it doesn't use 18 for
     * anything and doesn't appear to have ever used it for anything.)
     *
     * We define it as 18 on those platforms; it is, unfortunately, used
     * for DLT_CIP in Suse 6.3, so we don't define it as DLT_PFSYNC
     * in general.  As the packet format for it, like that for
     * DLT_PFLOG, is not only OS-dependent but OS-version-dependent,
     * we don't support printing it in tcpdump except on OSes that
     * have the relevant header files, so it's not that useful on
     * other platforms.
     */
    #if defined(__OpenBSD__) || defined(__NetBSD__) || defined(__DragonFly__) || defined(__APPLE__)
    #define DLT_PFSYNC	18
    #endif

and

    /*
     * Sigh.
     *
     * 121 was reserved for Siemens HiPath HDLC on 2002-01-25, as
     * requested by Tomas Kukosa.
     *
     * On 2004-02-25, a FreeBSD checkin to sys/net/bpf.h was made that
     * assigned 121 as DLT_PFSYNC.  In current versions, its libpcap
     * does DLT_ <-> LINKTYPE_ mapping, mapping DLT_PFSYNC to a
     * LINKTYPE_PFSYNC value of 246, so it should write out DLT_PFSYNC
     * dump files with 246 as the link-layer header type.  (Earlier
     * versions might not have done mapping, in which case they would
     * have written them out with a link-layer header type of 121.)
     *
     * OpenBSD, from which pf came, however, uses 18 for DLT_PFSYNC;
     * its libpcap does no DLT_ <-> LINKTYPE_ mapping, so it would
     * write out DLT_PFSYNC dump files with use 18 as the link-layer
     * header type.
     *
     * NetBSD, DragonFly BSD, and Darwin also use 18 for DLT_PFSYNC; in
     * current versions, their libpcaps do DLT_ <-> LINKTYPE_ mapping,
     * mapping DLT_PFSYNC to a LINKTYPE_PFSYNC value of 246, so they
     * should write out DLT_PFSYNC dump files with 246 as the link-layer
     * header type.  (Earlier versions might not have done mapping,
     * in which case they'd work the same way OpenBSD does, writing
     * them out with a link-layer header type of 18.)
     *
     * We'll define DLT_PFSYNC as:
     *
     *    18 on NetBSD, OpenBSD, DragonFly BSD, and Darwin;
     *
     *    121 on FreeBSD;
     *
     *    246 everywhere else.
     *
     * We'll define DLT_HHDLC as 121 on everything except for FreeBSD;
     * anybody who wants to compile, on FreeBSD, code that uses DLT_HHDLC
     * is out of luck.
     *
     * We'll define LINKTYPE_PFSYNC as 246 on *all* platforms, so that
     * savefiles written using *this* code won't use 18 or 121 for PFSYNC,
     * they'll all use 246.
     *
     * Code that uses pcap_datalink() to determine the link-layer header
     * type of a savefile won't, when built and run on FreeBSD, be able
     * to distinguish between LINKTYPE_PFSYNC and LINKTYPE_HHDLC capture
     * files, as pcap_datalink() will give 121 for both of them.  Code
     * that doesn't, such as the code in Wireshark, will be able to
     * distinguish between them.
     *
     * FreeBSD's libpcap won't map a link-layer header type of 18 - i.e.,
     * DLT_PFSYNC files from OpenBSD and possibly older versions of NetBSD,
     * DragonFly BSD, and macOS - to DLT_PFSYNC, so code built with FreeBSD's
     * libpcap won't treat those files as DLT_PFSYNC files.
     *
     * Other libpcaps won't map a link-layer header type of 121 to DLT_PFSYNC;
     * this means they can read DLT_HHDLC files, if any exist, but won't
     * treat pcap files written by any older versions of FreeBSD libpcap that
     * didn't map to 246 as DLT_PFSYNC files.
     */
    #ifdef __FreeBSD__
    #define DLT_PFSYNC		121
    #else
    #define DLT_HHDLC		121
    #endif

and

    /*
     * 246 is used as LINKTYPE_PFSYNC; do not use it for any other purpose.
     *
     * DLT_PFSYNC has different values on different platforms, and all of
     * them collide with something used elsewhere.  On platforms that
     * don't already define it, define it as 246.
     */
    #if !defined(__FreeBSD__) && !defined(__OpenBSD__) && !defined(__NetBSD__) && !defined(__DragonFly__) && !defined(__APPLE__)
    #define DLT_PFSYNC		246
    #endif

So those are the three count 'em three values for PFSYNC, all of which should be mapped to LINKTYPE_PFSYNC.

The other 1/2 variants are *other* cases where the numerical DLT_ values are platform-dependent.

All this stuff is why there are LINKTYPE_ values and DLT_ values and mappings between them.  (Thanks for provoking me to look this up; I now know that I should abandon my idea of having the next-generation capture and file reading/writing APIs in libpcap, with full pcapng support, use DLT_ values - they're just too problematic and platform-dependent.)

> 2. Is it correct to copy these defines over from the PCAP project to this project? Seems odd to me.

The LINKTYPE_ values currently aren't exported.  I wasn't going to export them when I did the new APIs, but, as per the above, I've changed my mind.  For now, though, you'll have to copy them.  As noted, they are *not* platform-dependent - anybody who changes any of them in their version of libpcap should be keelhauled, as it means they do not understand this *at all* - so it's perfectly OK to copy them.

The DLT_ values are platform-dependent.  You should get them from the platform's libpcap.  Not all of the ones tcpdump.org's libpcap defines will necessarily be defined by the platform's libpcap - if that means there's nothing to which a given LINKTYPE_ value can be mapped, you should think of that as meaning "this platform doesn't support that LINKTYPE_" and reject the file when opening it.

> Also where do they go? packet.h?

I'd define the LINKTYPE_ values in a .c file if they're only needed in one file, and in a non-public header file if they're needed in more than one file.

> 3. Question about C, as I'm usually py/java:
> 
> ```
> MolochPcapFileHdr_t cpy = pcapFileHeader; 
> modify(cpy); 
> memcpy(buf, &cpy, sizeof(MolochPcapFileHdr_t)); 
> ```
> 
> would be an acceptable, non-memory-leaking way of doing this, right? As the 24by copy-instance is only created on the stack?

Yes.

**Comment by rnbdsh** [comment]
Ohhh, now it makes sense!
Fixed it by importnig pcap/dlt.h, removing DLT_ imports leaving only defines for the LINKTYPE_

>I'd define the LINKTYPE_ values in a .c file if they're only needed in one file, and in a non-public header file if they're needed in more than one file.
Yes, they are only used in the packet-file, so the defines made most sense to me here too

So now I'm more certain that the MR can be reviewed.

**Comment by awick** [comment]
I don't think dlt.h can be used directly across all platforms, looks like you should use bpf.h which on some platforms/versions has the DLT values and on other platforms/versions bpf.h includes dlt.h for you.

Before making all these changes I do want to think a little more about what Moloch is actually trying to do.

**Comment by guyharris** [comment]
> I don't think dlt.h can be used directly across all platforms, looks like you should use bpf.h which on some platforms/versions has the DLT values and on other platforms/versions bpf.h includes dlt.h for you.

Yes - not all platforms have a dlt.h file.

But it's probably *best* to include pcap.h and let it include whatever is needed.

**Comment by guyharris** [comment]
> Before making all these changes I do want to think a little more about what Moloch is actually trying to do.

Write pcap files in a way that might be faster than what libpcap does?  I'm guessing that's why it has [its own code to write them](https://github.com/aol/moloch/blob/master/capture/writer-disk.c).

**Comment by rnbdsh** [comment]
>Before making all these changes I do want to think a little more about what Moloch is actually trying to do.
To be fair, it's mostly a moving around of the functionality of [dlt_to_linktype from libpcap](http://dog.tele.jp/winpcap/html/savefile_8c.html#a53) and renaming things. Functionally, it should be the same. But take your time, it's quite a complex issue, but the changes shouldn't make anything worse, in my head.

>I don't think dlt.h can be used directly across all platforms, looks like you should use bpf.h which on some platforms/versions has the DLT values and on other platforms/versions bpf.h includes dlt.h for you.

>But it's probably best to include pcap.h and let it include whatever is needed.
I just changed it to bpf. But feel free to change anything on the MR you want, you're the experts.

**Comment by awick** [comment]
> Write pcap files in a way that might be faster than what libpcap does? I'm guessing that's why it has [its own code to write them](https://github.com/aol/moloch/blob/master/capture/writer-disk.c).

Right, we support a bunch of different writing methods and DIRECT IO, encryption and other things.

Really we have 3 use cases
1. read in live using DLT_EN10MB (using libpcap, afpacket, pfring, ...) and write out to disk DLT_EN10MB.  This is the most common
2. read in files using libpcap in any format and NOT rewriting it
3. read in files using libpcap in any format and write back out using our code. This is what caused the current logic and is really and edge case.

The viewer code has to be able to read in whatever format the file is in too.  I wonder if we just shrink the number of formats supported that would make it easier.

**Comment by rnbwdsh** [comment]
So, can we merge this?
Because this would be required to properly include a normal, dynamically linked version of libpcap and get moloch one step closer to being deployable via normal packet managers.
The `writer-disk.c` should still work the same.
